### ISSUE TITLE
Pruning stopped working for daily backups

### ISSUE THREAD

**Issue by karamanliev** [enzingerm/snapborg#40]
Hello, thank you for the awesome tool!

I used snapborg without any problems for more than a year to backup my snapshots every night and it had zero issues. The backup to my borg repo still works fine, but for some reason pruning doesn't do anything and it just stopped working. I found out when I received an email that I'm out of free space from my borg repo provider.

 I'm just using  the default systemd `snapborg-backup-all` service. There are no errors in the logs, as I already mentioned backup works fine.

When I run `snapborg prune` (I tried with `sudo` as well) manually the output I get is something like this:
```
# snapborg prune                                                                                                                                                                                  
$ borg prune --list --keep-hourly 0 --keep-yearly 2 --keep-daily 5 --keep-monthly 3 --keep-last 0 --keep-weekly 4 --glob-archives 'root-*' myserver:root_backup
$ borg prune --list --keep-hourly 0 --keep-yearly 2 --keep-daily 5 --keep-monthly 3 --keep-last 0 --keep-weekly 4 --glob-archives 'home-*' myserver:home_backup
```
That does nothing. When I run the `borg prune` command manually the pruning actually works:
```
borg prune --list --keep-weekly 4 --keep-last 0 --keep-hourly 0 --keep-yearly 2 --keep-daily 5 --keep-monthly 3 --glob-archives 'home-*' myserver:home_backup                             
Enter passphrase for key ssh://myserver/./home_backup: *******************
Keeping archive (rule: daily #1):            home-4678-2025-03-26T18:00:00        Wed, 2025-03-26 18:00:00 [454a195507570a44cbc7440ea2829a85945f0957a31a9be4049716ae98cd6a09]
Pruning archive (1/7):                       home-4667-2025-03-26T02:00:03        Wed, 2025-03-26 02:00:03 [78da28bf1a8edeb481be14ac57b598f9ea8df595ea4df975146e0b7f01d49ef6]
Keeping archive (rule: daily #2):            home-4643-2025-03-25T02:00:09        Tue, 2025-03-25 02:00:09 [6954cca0c450aa4f23fd24229d34297b69fed7f981f8cfb2552938192a327f0d]
Keeping archive (rule: daily #3):            home-4636-2025-03-24T08:45:00        Mon, 2025-03-24 08:45:00 [df641338c6b1d2d12c5fc0c26d313ec8d9bcbb6b3e9c1c3ec94ddedee7a4a5c8]
```

Here's the config I'm using:
```yaml
configs:
  - name: root
    repo: myserver:root_backup
    fault_tolerant_mode: false
    last_backup_max_age: 0d
    storage:
      encryption: repokey-blake2
      encryption_passphrase: /path/to/root/passphrase
      compression: auto,lz4

    retention:
      keep_last: 0
      keep_hourly: 0
      keep_daily: 5
      keep_weekly: 4
      keep_monthly: 3
      keep_yearly: 2

    exclude_patterns: []

  - name: home
    repo: myserver:home_backup
    fault_tolerant_mode: false
    last_backup_max_age: 0d
    storage:
      encryption: repokey-blake2
      encryption_passphrase: /path/to/home/passphrase
      compression: auto,lz4

    retention:
      keep_last: 0
      keep_hourly: 0
      keep_daily: 5
      keep_weekly: 4
      keep_monthly: 3
      keep_yearly: 2

    exclude_patterns: []
```

I'm trying to solve this for 2-3 days now, without any luck.
